Creator "Graphes::Utils::GMLParser"
graph [
  comment "This is a graph generated by Graphes"
  node [
    id 0
    label "*"
    weight 0.0
    graphics [
	   x 40.0
	   y 260.0
	   w 51.0
	   h 51.0
	   type "rectangle"
    ]
  ]
  node [
    id 1
    label "*"
    weight 0.0
    graphics [
	   x 120.65879599942517
	   y 162.28665817578633
	   w 51.0
	   h 51.0
	   type "rectangle"
    ]
  ]
  node [
    id 2
    label "*"
    weight 0.0
    graphics [
	   x 18.618796854406618
	   y 124.84665702056883
	   w 51.0
	   h 51.0
	   type "rectangle"
    ]
  ]
  node [
    id 3
    label "*"
    weight 0.0
    graphics [
	   x 176.63912613439166
	   y -35.962430767866515
	   w 51.0
	   h 51.0
	   type "rectangle"
    ]
  ]
  edge [ 
    id 0
    source 0
    target 1
    label "TVCG"
    subgraph 0
    graphics [
	   arrow "last"
    ]
  ]
  edge [ 
    id 0
    source 1
    target 2
    label "InfoVis"
    subgraph 1
    graphics [
	   arrow "last"
    ]
  ]
  edge [ 
    id 0
    source 1
    target 2
    label "CGF"
    subgraph 2
    graphics [
	   arrow "last"
    ]
  ]
  edge [ 
    id 5
    source 2
    target 3
    label "TVCG"
    subgraph 0
    graphics [
	   arrow "last"
    ]
  ]
]
